const std = @import("std");
const builtin = @import("builtin");
const platform = @import("../platform.zig");

pub const utils = @import("utils.zig");

pub const c = @cImport({
    switch (builtin.os.tag) {
        .linux => @cDefine("VK_USE_PLATFORM_XLIB_KHR", {}),
        else => @compileError("platform not supported"),
    }

    @cInclude("vulkan/vulkan.h");
});

pub const required_device_extensions: [2][*:0]const u8 = .{
    c.VK_KHR_SWAPCHAIN_EXTENSION_NAME,
    c.VK_EXT_SWAPCHAIN_MAINTENANCE_1_EXTENSION_NAME,
};

pub const Error = error{
    VK_NOT_READY,
    VK_TIMEOUT,
    VK_EVENT_SET,
    VK_EVENT_RESET,
    VK_INCOMPLETE,
    VK_ERROR_OUT_OF_HOST_MEMORY,
    VK_ERROR_OUT_OF_DEVICE_MEMORY,
    VK_ERROR_INITIALIZATION_FAILED,
    VK_ERROR_DEVICE_LOST,
    VK_ERROR_MEMORY_MAP_FAILED,
    VK_ERROR_LAYER_NOT_PRESENT,
    VK_ERROR_EXTENSION_NOT_PRESENT,
    VK_ERROR_FEATURE_NOT_PRESENT,
    VK_ERROR_INCOMPATIBLE_DRIVER,
    VK_ERROR_TOO_MANY_OBJECTS,
    VK_ERROR_FORMAT_NOT_SUPPORTED,
    VK_ERROR_FRAGMENTED_POOL,
    VK_ERROR_UNKNOWN,
    VK_ERROR_OUT_OF_POOL_MEMORY,
    VK_ERROR_INVALID_EXTERNAL_HANDLE,
    VK_ERROR_FRAGMENTATION,
    VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,
    VK_PIPELINE_COMPILE_REQUIRED,
    VK_ERROR_NOT_PERMITTED,
    VK_ERROR_SURFACE_LOST_KHR,
    VK_ERROR_NATIVE_WINDOW_IN_USE_KHR,
    VK_SUBOPTIMAL_KHR,
    VK_ERROR_OUT_OF_DATE_KHR,
    VK_ERROR_INCOMPATIBLE_DISPLAY_KHR,
    VK_ERROR_VALIDATION_FAILED_EXT,
    VK_ERROR_INVALID_SHADER_NV,
    VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR,
    VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR,
    VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR,
    VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR,
    VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR,
    VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR,
    VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT,
    VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT,
    VK_THREAD_IDLE_KHR,
    VK_THREAD_DONE_KHR,
    VK_OPERATION_DEFERRED_KHR,
    VK_OPERATION_NOT_DEFERRED_KHR,
    VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR,
    VK_ERROR_COMPRESSION_EXHAUSTED_EXT,
    VK_INCOMPATIBLE_SHADER_BINARY_EXT,
    VK_PIPELINE_BINARY_MISSING_KHR,
    VK_ERROR_NOT_ENOUGH_SPACE_KHR,
};

pub fn wrap(result: c.VkResult) Error!void {
    if (result == c.VK_SUCCESS) {
        return;
    }

    return switch (result) {
        c.VK_NOT_READY => Error.VK_NOT_READY,
        c.VK_TIMEOUT => Error.VK_TIMEOUT,
        c.VK_EVENT_SET => Error.VK_EVENT_SET,
        c.VK_EVENT_RESET => Error.VK_EVENT_RESET,
        c.VK_INCOMPLETE => Error.VK_INCOMPLETE,
        c.VK_ERROR_OUT_OF_HOST_MEMORY => Error.VK_ERROR_OUT_OF_HOST_MEMORY,
        c.VK_ERROR_OUT_OF_DEVICE_MEMORY => Error.VK_ERROR_OUT_OF_DEVICE_MEMORY,
        c.VK_ERROR_INITIALIZATION_FAILED => Error.VK_ERROR_INITIALIZATION_FAILED,
        c.VK_ERROR_DEVICE_LOST => Error.VK_ERROR_DEVICE_LOST,
        c.VK_ERROR_MEMORY_MAP_FAILED => Error.VK_ERROR_MEMORY_MAP_FAILED,
        c.VK_ERROR_LAYER_NOT_PRESENT => Error.VK_ERROR_LAYER_NOT_PRESENT,
        c.VK_ERROR_EXTENSION_NOT_PRESENT => Error.VK_ERROR_EXTENSION_NOT_PRESENT,
        c.VK_ERROR_FEATURE_NOT_PRESENT => Error.VK_ERROR_FEATURE_NOT_PRESENT,
        c.VK_ERROR_INCOMPATIBLE_DRIVER => Error.VK_ERROR_INCOMPATIBLE_DRIVER,
        c.VK_ERROR_TOO_MANY_OBJECTS => Error.VK_ERROR_TOO_MANY_OBJECTS,
        c.VK_ERROR_FORMAT_NOT_SUPPORTED => Error.VK_ERROR_FORMAT_NOT_SUPPORTED,
        c.VK_ERROR_FRAGMENTED_POOL => Error.VK_ERROR_FRAGMENTED_POOL,
        c.VK_ERROR_UNKNOWN => Error.VK_ERROR_UNKNOWN,
        c.VK_ERROR_OUT_OF_POOL_MEMORY => Error.VK_ERROR_OUT_OF_POOL_MEMORY,
        c.VK_ERROR_INVALID_EXTERNAL_HANDLE => Error.VK_ERROR_INVALID_EXTERNAL_HANDLE,
        c.VK_ERROR_FRAGMENTATION => Error.VK_ERROR_FRAGMENTATION,
        c.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS => Error.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,
        c.VK_PIPELINE_COMPILE_REQUIRED => Error.VK_PIPELINE_COMPILE_REQUIRED,
        c.VK_ERROR_NOT_PERMITTED => Error.VK_ERROR_NOT_PERMITTED,
        c.VK_ERROR_SURFACE_LOST_KHR => Error.VK_ERROR_SURFACE_LOST_KHR,
        c.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR => Error.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR,
        c.VK_SUBOPTIMAL_KHR => Error.VK_SUBOPTIMAL_KHR,
        c.VK_ERROR_OUT_OF_DATE_KHR => Error.VK_ERROR_OUT_OF_DATE_KHR,
        c.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR => Error.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR,
        c.VK_ERROR_VALIDATION_FAILED_EXT => Error.VK_ERROR_VALIDATION_FAILED_EXT,
        c.VK_ERROR_INVALID_SHADER_NV => Error.VK_ERROR_INVALID_SHADER_NV,
        c.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR => Error.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR,
        c.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR => Error.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR,
        c.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR => Error.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR,
        c.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR => Error.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR,
        c.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR => Error.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR,
        c.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR => Error.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR,
        c.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT => Error.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT,
        c.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT => Error.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT,
        c.VK_THREAD_IDLE_KHR => Error.VK_THREAD_IDLE_KHR,
        c.VK_THREAD_DONE_KHR => Error.VK_THREAD_DONE_KHR,
        c.VK_OPERATION_DEFERRED_KHR => Error.VK_OPERATION_DEFERRED_KHR,
        c.VK_OPERATION_NOT_DEFERRED_KHR => Error.VK_OPERATION_NOT_DEFERRED_KHR,
        c.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR => Error.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR,
        c.VK_ERROR_COMPRESSION_EXHAUSTED_EXT => Error.VK_ERROR_COMPRESSION_EXHAUSTED_EXT,
        c.VK_INCOMPATIBLE_SHADER_BINARY_EXT => Error.VK_INCOMPATIBLE_SHADER_BINARY_EXT,
        c.VK_PIPELINE_BINARY_MISSING_KHR => Error.VK_PIPELINE_BINARY_MISSING_KHR,
        c.VK_ERROR_NOT_ENOUGH_SPACE_KHR => Error.VK_ERROR_NOT_ENOUGH_SPACE_KHR,
        else => Error.VK_ERROR_UNKNOWN,
    };
}
